<script setup lang="ts">
import { computed, ref } from "vue";

definePageMeta({
  layout: "dashboard",
});

type StatusType = "in-progress" | "planned" | "exploring";

type Feature = {
  id: number;
  icon: string;
  title: string;
  description: string;
  longDescription: string;
  status: StatusType;
  eta: string;
  category: string;
  upvotes: number;
};

const features: Feature[] = [
  {
    id: 1,
    icon: "i-lucide-brain-circuit",
    title: "AI Study Plans",
    description:
      "Personalized study roadmaps generated by AI based on your goals, deadlines, and learning pace.",
    longDescription:
      "Our AI will analyze your uploaded materials, project deadlines, and past performance to build a day-by-day study plan. It adapts in real time as you progress, recommending when to review, take breaks, and switch topics for optimal retention.",
    status: "in-progress",
    eta: "Q2 2026",
    category: "AI",
    upvotes: 342,
  },
  {
    id: 2,
    icon: "i-lucide-users",
    title: "Collaborative Study Rooms",
    description:
      "Real-time study rooms where you can work with classmates, share notes, and discuss topics.",
    longDescription:
      "Create or join virtual study rooms with real-time document collaboration, shared whiteboards, voice chat, and a group AI assistant. Perfect for group projects, exam prep sessions, or accountability partnerships.",
    status: "in-progress",
    eta: "Q2 2026",
    category: "Social",
    upvotes: 287,
  },
  {
    id: 3,
    icon: "i-lucide-bar-chart-3",
    title: "Advanced Analytics Dashboard",
    description:
      "Deep insights into your study habits, strengths, weaknesses, and progress over time.",
    longDescription:
      "Track learning velocity, identify knowledge gaps with heat maps, compare performance across subjects, and get AI-powered recommendations on where to focus. Includes weekly and monthly reports with exportable data.",
    status: "in-progress",
    eta: "Q2 2026",
    category: "Analytics",
    upvotes: 219,
  },
  {
    id: 4,
    icon: "i-lucide-smartphone",
    title: "Mobile App (iOS & Android)",
    description:
      "Take your learning on the go with native mobile apps featuring offline access and push notifications.",
    longDescription:
      "A full-featured mobile companion with offline material access, flashcard mode for commutes, push notifications for study reminders, and camera-based document scanning to quickly add new materials.",
    status: "planned",
    eta: "Q3 2026",
    category: "Platform",
    upvotes: 456,
  },
  {
    id: 5,
    icon: "i-lucide-mic",
    title: "Voice-Powered AI Tutor",
    description:
      "Have natural voice conversations with your AI tutor for hands-free studying.",
    longDescription:
      "Speak to your AI tutor like a real teacher. Ask questions, request explanations, and get verbal quizzes. Supports multiple languages and works well for auditory learners.",
    status: "planned",
    eta: "Q3 2026",
    category: "AI",
    upvotes: 198,
  },
  {
    id: 6,
    icon: "i-lucide-video",
    title: "Video Lecture Summarizer",
    description:
      "Upload or link lecture recordings and get AI-generated summaries, key points, and flashcards.",
    longDescription:
      "Paste a YouTube link or upload a lecture video. Our AI transcribes it, extracts key concepts, generates timestamped notes, and creates flashcards and practice questions automatically.",
    status: "planned",
    eta: "Q3 2026",
    category: "AI",
    upvotes: 378,
  },
  {
    id: 7,
    icon: "i-lucide-globe",
    title: "Multi-Language Support",
    description: "Full platform localization and AI interactions in 20+ languages.",
    longDescription:
      "Study in your native language or any language you are learning. The entire interface, AI responses, and generated content will be available in 20+ languages.",
    status: "exploring",
    eta: "Q4 2026",
    category: "Platform",
    upvotes: 167,
  },
  {
    id: 8,
    icon: "i-lucide-share-2",
    title: "Community Marketplace",
    description:
      "Share and discover study materials, templates, and question banks created by other students.",
    longDescription:
      "Browse a curated marketplace of study guides, flashcard decks, project templates, and practice exams uploaded by the community. Rate and review resources, follow top contributors, and share your own materials.",
    status: "exploring",
    eta: "Q4 2026",
    category: "Social",
    upvotes: 234,
  },
  {
    id: 9,
    icon: "i-lucide-layers",
    title: "Spaced Repetition Engine",
    description:
      "Science-backed flashcard system that schedules reviews at optimal intervals for retention.",
    longDescription:
      "Automatically converts notes into smart flashcards. Uses the SM-2 algorithm to schedule reviews right before you forget, maximizing memory retention with minimal study time.",
    status: "planned",
    eta: "Q3 2026",
    category: "Learning",
    upvotes: 312,
  },
  {
    id: 10,
    icon: "i-lucide-bot",
    title: "Assignment Auto-Checker",
    description:
      "Submit drafts and get instant AI feedback on grammar, accuracy, structure, and citations.",
    longDescription:
      "Upload drafts or problem sets. The AI checks for accuracy, grammar, logical flow, proper citations, and provides constructive feedback with suggested improvements.",
    status: "exploring",
    eta: "2027",
    category: "AI",
    upvotes: 289,
  },
  {
    id: 11,
    icon: "i-lucide-graduation-cap",
    title: "Certification & Badges",
    description:
      "Earn verifiable certificates and skill badges as you complete study milestones.",
    longDescription:
      "Complete structured learning paths and pass assessments to earn digital certificates and badges. Share them on LinkedIn or your portfolio.",
    status: "exploring",
    eta: "2027",
    category: "Learning",
    upvotes: 145,
  },
  {
    id: 12,
    icon: "i-lucide-file-text",
    title: "Smart Note-Taking",
    description:
      "Rich text editor with AI auto-formatting, concept linking, and knowledge graph visualization.",
    longDescription:
      "A powerful note editor that understands your content. It auto-formats headings, highlights key terms, links related concepts across your notes, and builds a visual knowledge graph.",
    status: "in-progress",
    eta: "Q2 2026",
    category: "Learning",
    upvotes: 401,
  },
];

const statusConfig: Record<
  StatusType,
  { label: string; color: string; chip: string; icon: string }
> = {
  "in-progress": {
    label: "In Progress",
    color: "text-emerald-600",
    chip: "bg-emerald-500/10",
    icon: "i-lucide-wrench",
  },
  planned: {
    label: "Planned",
    color: "text-blue-600",
    chip: "bg-blue-500/10",
    icon: "i-lucide-clock",
  },
  exploring: {
    label: "Exploring",
    color: "text-amber-600",
    chip: "bg-amber-500/10",
    icon: "i-lucide-lightbulb",
  },
};

const categories = ["All", "AI", "Social", "Analytics", "Platform", "Learning"];

const selectedCategory = ref("All");
const selectedStatus = ref<StatusType | "all">("all");
const expandedFeature = ref<number | null>(null);
const upvotedFeatures = ref(new Set<number>());
const notifyFeatures = ref(new Set<number>());

const filteredFeatures = computed(() =>
  features.filter((item) => {
    const matchCategory =
      selectedCategory.value === "All" || item.category === selectedCategory.value;
    const matchStatus =
      selectedStatus.value === "all" || item.status === selectedStatus.value;
    return matchCategory && matchStatus;
  }),
);

const inProgressCount = computed(
  () => features.filter((f) => f.status === "in-progress").length,
);
const plannedCount = computed(
  () => features.filter((f) => f.status === "planned").length,
);
const exploringCount = computed(
  () => features.filter((f) => f.status === "exploring").length,
);

const toggleUpvote = (id: number) => {
  const next = new Set(upvotedFeatures.value);
  if (next.has(id)) {
    next.delete(id);
  } else {
    next.add(id);
  }
  upvotedFeatures.value = next;
};

const toggleNotify = (id: number) => {
  const next = new Set(notifyFeatures.value);
  if (next.has(id)) {
    next.delete(id);
  } else {
    next.add(id);
  }
  notifyFeatures.value = next;
};
</script>

<template>
  <DashboardBodyLayout
    title="Coming Soon"
    description="Upcoming features we are building to supercharge your learning."
  >
    <div class="space-y-8">
      <UCard class="relative overflow-hidden border-default">
        <div class="absolute -right-10 -top-10 h-52 w-52 rounded-full bg-primary/5" />
        <div class="absolute -bottom-10 -left-10 h-44 w-44 rounded-full bg-primary/5" />
        <div class="relative space-y-4">
          <div class="flex items-center gap-3">
            <div
              class="flex h-12 w-12 items-center justify-center rounded-xl bg-primary text-primary-foreground"
            >
              <UIcon name="i-lucide-rocket" class="h-6 w-6" />
            </div>
            <div>
              <h2 class="text-3xl font-bold text-foreground">Coming Soon</h2>
              <p class="text-sm text-muted-foreground">
                Here is what is in progress, planned, and being explored.
              </p>
            </div>
          </div>
          <p class="max-w-2xl text-muted-foreground">
            Upvote features you want most and we will prioritize the roadmap.
            We will also notify you when a feature ships.
          </p>
        </div>
      </UCard>

      <div class="grid grid-cols-1 gap-4 md:grid-cols-3">
        <UButton
          color="neutral"
          variant="outline"
          class="justify-start gap-4 py-5"
          :class="
            selectedStatus === 'in-progress'
              ? 'border-emerald-500/50 bg-emerald-500/5'
              : 'border-default'
          "
          @click="
            selectedStatus =
              selectedStatus === 'in-progress' ? 'all' : 'in-progress'
          "
        >
          <div
            class="flex h-12 w-12 items-center justify-center rounded-xl bg-emerald-500/10"
          >
            <UIcon name="i-lucide-wrench" class="h-6 w-6 text-emerald-600" />
          </div>
          <div class="text-left">
            <div class="text-2xl font-bold text-foreground">
              {{ inProgressCount }}
            </div>
            <div class="text-sm text-muted-foreground">In Progress</div>
          </div>
        </UButton>
        <UButton
          color="neutral"
          variant="outline"
          class="justify-start gap-4 py-5"
          :class="
            selectedStatus === 'planned'
              ? 'border-blue-500/50 bg-blue-500/5'
              : 'border-default'
          "
          @click="
            selectedStatus = selectedStatus === 'planned' ? 'all' : 'planned'
          "
        >
          <div
            class="flex h-12 w-12 items-center justify-center rounded-xl bg-blue-500/10"
          >
            <UIcon name="i-lucide-clock" class="h-6 w-6 text-blue-600" />
          </div>
          <div class="text-left">
            <div class="text-2xl font-bold text-foreground">
              {{ plannedCount }}
            </div>
            <div class="text-sm text-muted-foreground">Planned</div>
          </div>
        </UButton>
        <UButton
          color="neutral"
          variant="outline"
          class="justify-start gap-4 py-5"
          :class="
            selectedStatus === 'exploring'
              ? 'border-amber-500/50 bg-amber-500/5'
              : 'border-default'
          "
          @click="
            selectedStatus =
              selectedStatus === 'exploring' ? 'all' : 'exploring'
          "
        >
          <div
            class="flex h-12 w-12 items-center justify-center rounded-xl bg-amber-500/10"
          >
            <UIcon
              name="i-lucide-lightbulb"
              class="h-6 w-6 text-amber-600"
            />
          </div>
          <div class="text-left">
            <div class="text-2xl font-bold text-foreground">
              {{ exploringCount }}
            </div>
            <div class="text-sm text-muted-foreground">Exploring</div>
          </div>
        </UButton>
      </div>

      <div class="flex items-center gap-2 overflow-x-auto pb-1">
        <UButton
          v-for="cat in categories"
          :key="cat"
          size="sm"
          :color="selectedCategory === cat ? 'primary' : 'neutral'"
          :variant="selectedCategory === cat ? 'solid' : 'outline'"
          class="whitespace-nowrap"
          @click="selectedCategory = cat"
        >
          {{ cat }}
        </UButton>
      </div>

      <div class="space-y-4">
        <UCard
          v-for="feature in filteredFeatures"
          :key="feature.id"
          class="border-default"
        >
          <div class="flex flex-col gap-4 md:flex-row md:items-start">
            <div
              class="flex h-12 w-12 flex-shrink-0 items-center justify-center rounded-xl bg-primary/10 text-primary"
            >
              <UIcon :name="feature.icon" class="h-6 w-6" />
            </div>

            <div class="flex-1 space-y-2">
              <div class="flex flex-wrap items-center gap-2">
                <h3 class="text-lg font-semibold text-foreground">
                  {{ feature.title }}
                </h3>
                <span
                  class="inline-flex items-center gap-1.5 rounded-full px-2.5 py-0.5 text-xs font-medium"
                  :class="[
                    statusConfig[feature.status].chip,
                    statusConfig[feature.status].color,
                  ]"
                >
                  <UIcon
                    :name="statusConfig[feature.status].icon"
                    class="h-3 w-3"
                  />
                  {{ statusConfig[feature.status].label }}
                </span>
                <span
                  class="rounded-full bg-muted px-2.5 py-0.5 text-xs text-muted-foreground"
                >
                  {{ feature.category }}
                </span>
              </div>
              <p class="text-sm text-muted-foreground">
                {{ feature.description }}
              </p>

              <div v-if="expandedFeature === feature.id" class="space-y-3">
                <div class="rounded-lg bg-muted/50 p-4 text-sm text-muted-foreground">
                  {{ feature.longDescription }}
                </div>
                <div class="flex items-center gap-2 text-xs text-muted-foreground">
                  <UIcon name="i-lucide-clock" class="h-3.5 w-3.5" />
                  <span>Estimated launch: {{ feature.eta }}</span>
                </div>
              </div>

              <UButton
                size="sm"
                variant="ghost"
                color="primary"
                class="px-0"
                @click="
                  expandedFeature =
                    expandedFeature === feature.id ? null : feature.id
                "
              >
                {{ expandedFeature === feature.id ? "Show less" : "Learn more" }}
              </UButton>
            </div>

            <div class="flex items-center gap-2 md:flex-col md:items-end">
              <UButton
                size="sm"
                :color="upvotedFeatures.has(feature.id) ? 'primary' : 'neutral'"
                :variant="
                  upvotedFeatures.has(feature.id) ? 'soft' : 'outline'
                "
                class="gap-2"
                @click="toggleUpvote(feature.id)"
              >
                <UIcon
                  name="i-lucide-zap"
                  :class="upvotedFeatures.has(feature.id) ? 'text-primary' : ''"
                />
                {{
                  feature.upvotes + (upvotedFeatures.has(feature.id) ? 1 : 0)
                }}
              </UButton>
              <UButton
                size="sm"
                :color="
                  notifyFeatures.has(feature.id) ? 'primary' : 'neutral'
                "
                :variant="
                  notifyFeatures.has(feature.id) ? 'soft' : 'outline'
                "
                class="gap-2"
                @click="toggleNotify(feature.id)"
              >
                <UIcon
                  :name="
                    notifyFeatures.has(feature.id)
                      ? 'i-lucide-check'
                      : 'i-lucide-bell'
                  "
                />
                <span class="hidden md:inline">
                  {{ notifyFeatures.has(feature.id) ? "Subscribed" : "Notify me" }}
                </span>
              </UButton>
            </div>
          </div>
        </UCard>

        <UCard v-if="filteredFeatures.length === 0" class="border-default">
          <div class="flex flex-col items-center gap-4 py-10 text-center">
            <div
              class="flex h-14 w-14 items-center justify-center rounded-2xl bg-muted text-muted-foreground"
            >
              <UIcon name="i-lucide-sparkles" class="h-7 w-7" />
            </div>
            <div>
              <p class="font-semibold text-foreground">
                No features match your filters
              </p>
              <p class="text-sm text-muted-foreground">
                Adjust the category or status to see more items.
              </p>
            </div>
            <UButton
              color="primary"
              variant="solid"
              @click="
                selectedCategory = 'All';
                selectedStatus = 'all';
              "
            >
              Reset Filters
            </UButton>
          </div>
        </UCard>
      </div>

      <UCard class="border-default">
        <div class="flex flex-col items-center gap-4 md:flex-row md:justify-between">
          <div class="flex items-center gap-4">
            <div
              class="flex h-12 w-12 items-center justify-center rounded-xl bg-primary/10 text-primary"
            >
              <UIcon name="i-lucide-sparkles" class="h-6 w-6" />
            </div>
            <div>
              <h3 class="font-semibold text-foreground">
                Have an idea we have not thought of?
              </h3>
              <p class="text-sm text-muted-foreground">
                Send it through Feedback and we will review it.
              </p>
            </div>
          </div>
          <UButton
            to="/dashboard/feedback"
            color="primary"
            icon="i-lucide-arrow-right"
          >
            Suggest a Feature
          </UButton>
        </div>
      </UCard>
    </div>
  </DashboardBodyLayout>
</template>
